// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+575,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+576,0,"GPIO",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("top", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+575,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+576,0,"GPIO",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+577,0,"PC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+578,0,"data_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+579,0,"data_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+580,0,"data_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+581,0,"ins_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+1,0,"ins_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+2,0,"ins_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+3,0,"rs0_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+4,0,"rs1_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+5,0,"rd_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+6,0,"rs0_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+7,0,"rs1_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+8,0,"rd_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+9,0,"exec_type",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+10,0,"immediate",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+11,0,"reg_we",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+12,0,"data_mem_width",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+13,0,"data_mem_we",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+14,0,"data_mem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+15,0,"data_mem_sign",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+16,0,"data_mem_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+17,0,"data_mem_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+18,0,"data_mem_reg_we",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+19,0,"data_mem_reg_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+20,0,"data_mem_reg_width",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+21,0,"jump_en",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+22,0,"jump_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+23,0,"ins_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+1,0,"fd_ins",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+582,0,"ins_we",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+583,0,"data_we",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->pushPrefix("DRAM", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+575,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"sign",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+14,0,"addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+12,0,"data_width",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+13,0,"we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+16,0,"in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+17,0,"out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+576,0,"GPIO",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("mem", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 256; ++i) {
        tracep->declBus(c+24+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+280,0,"word_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+281,0,"is_mmio_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("DU", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+575,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+1,0,"fd_ins",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+9,0,"exec_type",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+282,0,"rs0",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+283,0,"rs1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+284,0,"rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+10,0,"immediate",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("EU", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+575,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+2,0,"PC",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+9,0,"exec_type",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 5,0);
    tracep->declBus(c+6,0,"rs0",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+7,0,"rs1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+284,0,"rd_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+10,0,"immediate",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+8,0,"rd",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+23,0,"ins_ready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+11,0,"we",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+18,0,"mem_reg_we",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+19,0,"reg_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+20,0,"reg_width",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+13,0,"mem_we",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+14,0,"mem_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+16,0,"mem_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+12,0,"mem_width",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+15,0,"mem_sign",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+21,0,"jump_en",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+22,0,"jump_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+285,0,"target_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("FU", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+575,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+1,0,"ins_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+21,0,"jump_en",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+22,0,"jump_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+2,0,"ins_ram_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+1,0,"ins_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+23,0,"ins_ready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+2,0,"PC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("IRAM", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+575,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+2,0,"addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+581,0,"in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+582,0,"we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+1,0,"out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("mem", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 256; ++i) {
        tracep->declBus(c+286+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+542,0,"word_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("reg_file", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+575,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+282,0,"rs0_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+283,0,"rs1_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+284,0,"rd_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+8,0,"rd_data",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+11,0,"we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+6,0,"rs0_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+7,0,"rs1_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+18,0,"mem_we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+19,0,"reg_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+20,0,"data_width",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+17,0,"mem_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("regs", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+543+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedVcd* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+577,(vlSelfRef.top__DOT__PC),32);
    bufp->fullIData(oldp+578,(vlSelfRef.top__DOT__data_in),32);
    bufp->fullIData(oldp+579,(vlSelfRef.top__DOT__data_out),32);
    bufp->fullIData(oldp+580,(vlSelfRef.top__DOT__data_addr),32);
    bufp->fullIData(oldp+581,(vlSelfRef.top__DOT__ins_in),32);
    bufp->fullCData(oldp+582,(vlSelfRef.top__DOT__ins_we),4);
    bufp->fullCData(oldp+583,(vlSelfRef.top__DOT__data_we),4);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+1,(vlSelfRef.top__DOT__ins_out),32);
    bufp->fullIData(oldp+2,(vlSelfRef.top__DOT__FU__DOT__PC),32);
    bufp->fullIData(oldp+3,((0x1fU & (vlSelfRef.top__DOT__ins_out 
                                      >> 0xfU))),32);
    bufp->fullIData(oldp+4,((0x1fU & (vlSelfRef.top__DOT__ins_out 
                                      >> 0x14U))),32);
    bufp->fullIData(oldp+5,((0x1fU & (vlSelfRef.top__DOT__ins_out 
                                      >> 7U))),32);
    bufp->fullIData(oldp+6,(vlSelfRef.top__DOT__rs0_data),32);
    bufp->fullIData(oldp+7,(vlSelfRef.top__DOT__rs1_data),32);
    bufp->fullIData(oldp+8,(vlSelfRef.top__DOT__rd_data),32);
    bufp->fullCData(oldp+9,(vlSelfRef.top__DOT__exec_type),6);
    bufp->fullIData(oldp+10,(vlSelfRef.top__DOT__immediate),32);
    bufp->fullBit(oldp+11,(vlSelfRef.top__DOT__reg_we));
    bufp->fullCData(oldp+12,(vlSelfRef.top__DOT__data_mem_width),3);
    bufp->fullCData(oldp+13,(vlSelfRef.top__DOT__data_mem_we),4);
    bufp->fullIData(oldp+14,(vlSelfRef.top__DOT__data_mem_addr),32);
    bufp->fullBit(oldp+15,(vlSelfRef.top__DOT__data_mem_sign));
    bufp->fullIData(oldp+16,(vlSelfRef.top__DOT__data_mem_in),32);
    bufp->fullIData(oldp+17,(vlSelfRef.top__DOT__data_mem_out),32);
    bufp->fullBit(oldp+18,(vlSelfRef.top__DOT__data_mem_reg_we));
    bufp->fullCData(oldp+19,(vlSelfRef.top__DOT__data_mem_reg_addr),5);
    bufp->fullCData(oldp+20,(vlSelfRef.top__DOT__data_mem_reg_width),3);
    bufp->fullBit(oldp+21,(vlSelfRef.top__DOT__jump_en));
    bufp->fullIData(oldp+22,(vlSelfRef.top__DOT__jump_addr),32);
    bufp->fullBit(oldp+23,(vlSelfRef.top__DOT__ins_ready));
    bufp->fullIData(oldp+24,(vlSelfRef.top__DOT__DRAM__DOT__mem[0]),32);
    bufp->fullIData(oldp+25,(vlSelfRef.top__DOT__DRAM__DOT__mem[1]),32);
    bufp->fullIData(oldp+26,(vlSelfRef.top__DOT__DRAM__DOT__mem[2]),32);
    bufp->fullIData(oldp+27,(vlSelfRef.top__DOT__DRAM__DOT__mem[3]),32);
    bufp->fullIData(oldp+28,(vlSelfRef.top__DOT__DRAM__DOT__mem[4]),32);
    bufp->fullIData(oldp+29,(vlSelfRef.top__DOT__DRAM__DOT__mem[5]),32);
    bufp->fullIData(oldp+30,(vlSelfRef.top__DOT__DRAM__DOT__mem[6]),32);
    bufp->fullIData(oldp+31,(vlSelfRef.top__DOT__DRAM__DOT__mem[7]),32);
    bufp->fullIData(oldp+32,(vlSelfRef.top__DOT__DRAM__DOT__mem[8]),32);
    bufp->fullIData(oldp+33,(vlSelfRef.top__DOT__DRAM__DOT__mem[9]),32);
    bufp->fullIData(oldp+34,(vlSelfRef.top__DOT__DRAM__DOT__mem[10]),32);
    bufp->fullIData(oldp+35,(vlSelfRef.top__DOT__DRAM__DOT__mem[11]),32);
    bufp->fullIData(oldp+36,(vlSelfRef.top__DOT__DRAM__DOT__mem[12]),32);
    bufp->fullIData(oldp+37,(vlSelfRef.top__DOT__DRAM__DOT__mem[13]),32);
    bufp->fullIData(oldp+38,(vlSelfRef.top__DOT__DRAM__DOT__mem[14]),32);
    bufp->fullIData(oldp+39,(vlSelfRef.top__DOT__DRAM__DOT__mem[15]),32);
    bufp->fullIData(oldp+40,(vlSelfRef.top__DOT__DRAM__DOT__mem[16]),32);
    bufp->fullIData(oldp+41,(vlSelfRef.top__DOT__DRAM__DOT__mem[17]),32);
    bufp->fullIData(oldp+42,(vlSelfRef.top__DOT__DRAM__DOT__mem[18]),32);
    bufp->fullIData(oldp+43,(vlSelfRef.top__DOT__DRAM__DOT__mem[19]),32);
    bufp->fullIData(oldp+44,(vlSelfRef.top__DOT__DRAM__DOT__mem[20]),32);
    bufp->fullIData(oldp+45,(vlSelfRef.top__DOT__DRAM__DOT__mem[21]),32);
    bufp->fullIData(oldp+46,(vlSelfRef.top__DOT__DRAM__DOT__mem[22]),32);
    bufp->fullIData(oldp+47,(vlSelfRef.top__DOT__DRAM__DOT__mem[23]),32);
    bufp->fullIData(oldp+48,(vlSelfRef.top__DOT__DRAM__DOT__mem[24]),32);
    bufp->fullIData(oldp+49,(vlSelfRef.top__DOT__DRAM__DOT__mem[25]),32);
    bufp->fullIData(oldp+50,(vlSelfRef.top__DOT__DRAM__DOT__mem[26]),32);
    bufp->fullIData(oldp+51,(vlSelfRef.top__DOT__DRAM__DOT__mem[27]),32);
    bufp->fullIData(oldp+52,(vlSelfRef.top__DOT__DRAM__DOT__mem[28]),32);
    bufp->fullIData(oldp+53,(vlSelfRef.top__DOT__DRAM__DOT__mem[29]),32);
    bufp->fullIData(oldp+54,(vlSelfRef.top__DOT__DRAM__DOT__mem[30]),32);
    bufp->fullIData(oldp+55,(vlSelfRef.top__DOT__DRAM__DOT__mem[31]),32);
    bufp->fullIData(oldp+56,(vlSelfRef.top__DOT__DRAM__DOT__mem[32]),32);
    bufp->fullIData(oldp+57,(vlSelfRef.top__DOT__DRAM__DOT__mem[33]),32);
    bufp->fullIData(oldp+58,(vlSelfRef.top__DOT__DRAM__DOT__mem[34]),32);
    bufp->fullIData(oldp+59,(vlSelfRef.top__DOT__DRAM__DOT__mem[35]),32);
    bufp->fullIData(oldp+60,(vlSelfRef.top__DOT__DRAM__DOT__mem[36]),32);
    bufp->fullIData(oldp+61,(vlSelfRef.top__DOT__DRAM__DOT__mem[37]),32);
    bufp->fullIData(oldp+62,(vlSelfRef.top__DOT__DRAM__DOT__mem[38]),32);
    bufp->fullIData(oldp+63,(vlSelfRef.top__DOT__DRAM__DOT__mem[39]),32);
    bufp->fullIData(oldp+64,(vlSelfRef.top__DOT__DRAM__DOT__mem[40]),32);
    bufp->fullIData(oldp+65,(vlSelfRef.top__DOT__DRAM__DOT__mem[41]),32);
    bufp->fullIData(oldp+66,(vlSelfRef.top__DOT__DRAM__DOT__mem[42]),32);
    bufp->fullIData(oldp+67,(vlSelfRef.top__DOT__DRAM__DOT__mem[43]),32);
    bufp->fullIData(oldp+68,(vlSelfRef.top__DOT__DRAM__DOT__mem[44]),32);
    bufp->fullIData(oldp+69,(vlSelfRef.top__DOT__DRAM__DOT__mem[45]),32);
    bufp->fullIData(oldp+70,(vlSelfRef.top__DOT__DRAM__DOT__mem[46]),32);
    bufp->fullIData(oldp+71,(vlSelfRef.top__DOT__DRAM__DOT__mem[47]),32);
    bufp->fullIData(oldp+72,(vlSelfRef.top__DOT__DRAM__DOT__mem[48]),32);
    bufp->fullIData(oldp+73,(vlSelfRef.top__DOT__DRAM__DOT__mem[49]),32);
    bufp->fullIData(oldp+74,(vlSelfRef.top__DOT__DRAM__DOT__mem[50]),32);
    bufp->fullIData(oldp+75,(vlSelfRef.top__DOT__DRAM__DOT__mem[51]),32);
    bufp->fullIData(oldp+76,(vlSelfRef.top__DOT__DRAM__DOT__mem[52]),32);
    bufp->fullIData(oldp+77,(vlSelfRef.top__DOT__DRAM__DOT__mem[53]),32);
    bufp->fullIData(oldp+78,(vlSelfRef.top__DOT__DRAM__DOT__mem[54]),32);
    bufp->fullIData(oldp+79,(vlSelfRef.top__DOT__DRAM__DOT__mem[55]),32);
    bufp->fullIData(oldp+80,(vlSelfRef.top__DOT__DRAM__DOT__mem[56]),32);
    bufp->fullIData(oldp+81,(vlSelfRef.top__DOT__DRAM__DOT__mem[57]),32);
    bufp->fullIData(oldp+82,(vlSelfRef.top__DOT__DRAM__DOT__mem[58]),32);
    bufp->fullIData(oldp+83,(vlSelfRef.top__DOT__DRAM__DOT__mem[59]),32);
    bufp->fullIData(oldp+84,(vlSelfRef.top__DOT__DRAM__DOT__mem[60]),32);
    bufp->fullIData(oldp+85,(vlSelfRef.top__DOT__DRAM__DOT__mem[61]),32);
    bufp->fullIData(oldp+86,(vlSelfRef.top__DOT__DRAM__DOT__mem[62]),32);
    bufp->fullIData(oldp+87,(vlSelfRef.top__DOT__DRAM__DOT__mem[63]),32);
    bufp->fullIData(oldp+88,(vlSelfRef.top__DOT__DRAM__DOT__mem[64]),32);
    bufp->fullIData(oldp+89,(vlSelfRef.top__DOT__DRAM__DOT__mem[65]),32);
    bufp->fullIData(oldp+90,(vlSelfRef.top__DOT__DRAM__DOT__mem[66]),32);
    bufp->fullIData(oldp+91,(vlSelfRef.top__DOT__DRAM__DOT__mem[67]),32);
    bufp->fullIData(oldp+92,(vlSelfRef.top__DOT__DRAM__DOT__mem[68]),32);
    bufp->fullIData(oldp+93,(vlSelfRef.top__DOT__DRAM__DOT__mem[69]),32);
    bufp->fullIData(oldp+94,(vlSelfRef.top__DOT__DRAM__DOT__mem[70]),32);
    bufp->fullIData(oldp+95,(vlSelfRef.top__DOT__DRAM__DOT__mem[71]),32);
    bufp->fullIData(oldp+96,(vlSelfRef.top__DOT__DRAM__DOT__mem[72]),32);
    bufp->fullIData(oldp+97,(vlSelfRef.top__DOT__DRAM__DOT__mem[73]),32);
    bufp->fullIData(oldp+98,(vlSelfRef.top__DOT__DRAM__DOT__mem[74]),32);
    bufp->fullIData(oldp+99,(vlSelfRef.top__DOT__DRAM__DOT__mem[75]),32);
    bufp->fullIData(oldp+100,(vlSelfRef.top__DOT__DRAM__DOT__mem[76]),32);
    bufp->fullIData(oldp+101,(vlSelfRef.top__DOT__DRAM__DOT__mem[77]),32);
    bufp->fullIData(oldp+102,(vlSelfRef.top__DOT__DRAM__DOT__mem[78]),32);
    bufp->fullIData(oldp+103,(vlSelfRef.top__DOT__DRAM__DOT__mem[79]),32);
    bufp->fullIData(oldp+104,(vlSelfRef.top__DOT__DRAM__DOT__mem[80]),32);
    bufp->fullIData(oldp+105,(vlSelfRef.top__DOT__DRAM__DOT__mem[81]),32);
    bufp->fullIData(oldp+106,(vlSelfRef.top__DOT__DRAM__DOT__mem[82]),32);
    bufp->fullIData(oldp+107,(vlSelfRef.top__DOT__DRAM__DOT__mem[83]),32);
    bufp->fullIData(oldp+108,(vlSelfRef.top__DOT__DRAM__DOT__mem[84]),32);
    bufp->fullIData(oldp+109,(vlSelfRef.top__DOT__DRAM__DOT__mem[85]),32);
    bufp->fullIData(oldp+110,(vlSelfRef.top__DOT__DRAM__DOT__mem[86]),32);
    bufp->fullIData(oldp+111,(vlSelfRef.top__DOT__DRAM__DOT__mem[87]),32);
    bufp->fullIData(oldp+112,(vlSelfRef.top__DOT__DRAM__DOT__mem[88]),32);
    bufp->fullIData(oldp+113,(vlSelfRef.top__DOT__DRAM__DOT__mem[89]),32);
    bufp->fullIData(oldp+114,(vlSelfRef.top__DOT__DRAM__DOT__mem[90]),32);
    bufp->fullIData(oldp+115,(vlSelfRef.top__DOT__DRAM__DOT__mem[91]),32);
    bufp->fullIData(oldp+116,(vlSelfRef.top__DOT__DRAM__DOT__mem[92]),32);
    bufp->fullIData(oldp+117,(vlSelfRef.top__DOT__DRAM__DOT__mem[93]),32);
    bufp->fullIData(oldp+118,(vlSelfRef.top__DOT__DRAM__DOT__mem[94]),32);
    bufp->fullIData(oldp+119,(vlSelfRef.top__DOT__DRAM__DOT__mem[95]),32);
    bufp->fullIData(oldp+120,(vlSelfRef.top__DOT__DRAM__DOT__mem[96]),32);
    bufp->fullIData(oldp+121,(vlSelfRef.top__DOT__DRAM__DOT__mem[97]),32);
    bufp->fullIData(oldp+122,(vlSelfRef.top__DOT__DRAM__DOT__mem[98]),32);
    bufp->fullIData(oldp+123,(vlSelfRef.top__DOT__DRAM__DOT__mem[99]),32);
    bufp->fullIData(oldp+124,(vlSelfRef.top__DOT__DRAM__DOT__mem[100]),32);
    bufp->fullIData(oldp+125,(vlSelfRef.top__DOT__DRAM__DOT__mem[101]),32);
    bufp->fullIData(oldp+126,(vlSelfRef.top__DOT__DRAM__DOT__mem[102]),32);
    bufp->fullIData(oldp+127,(vlSelfRef.top__DOT__DRAM__DOT__mem[103]),32);
    bufp->fullIData(oldp+128,(vlSelfRef.top__DOT__DRAM__DOT__mem[104]),32);
    bufp->fullIData(oldp+129,(vlSelfRef.top__DOT__DRAM__DOT__mem[105]),32);
    bufp->fullIData(oldp+130,(vlSelfRef.top__DOT__DRAM__DOT__mem[106]),32);
    bufp->fullIData(oldp+131,(vlSelfRef.top__DOT__DRAM__DOT__mem[107]),32);
    bufp->fullIData(oldp+132,(vlSelfRef.top__DOT__DRAM__DOT__mem[108]),32);
    bufp->fullIData(oldp+133,(vlSelfRef.top__DOT__DRAM__DOT__mem[109]),32);
    bufp->fullIData(oldp+134,(vlSelfRef.top__DOT__DRAM__DOT__mem[110]),32);
    bufp->fullIData(oldp+135,(vlSelfRef.top__DOT__DRAM__DOT__mem[111]),32);
    bufp->fullIData(oldp+136,(vlSelfRef.top__DOT__DRAM__DOT__mem[112]),32);
    bufp->fullIData(oldp+137,(vlSelfRef.top__DOT__DRAM__DOT__mem[113]),32);
    bufp->fullIData(oldp+138,(vlSelfRef.top__DOT__DRAM__DOT__mem[114]),32);
    bufp->fullIData(oldp+139,(vlSelfRef.top__DOT__DRAM__DOT__mem[115]),32);
    bufp->fullIData(oldp+140,(vlSelfRef.top__DOT__DRAM__DOT__mem[116]),32);
    bufp->fullIData(oldp+141,(vlSelfRef.top__DOT__DRAM__DOT__mem[117]),32);
    bufp->fullIData(oldp+142,(vlSelfRef.top__DOT__DRAM__DOT__mem[118]),32);
    bufp->fullIData(oldp+143,(vlSelfRef.top__DOT__DRAM__DOT__mem[119]),32);
    bufp->fullIData(oldp+144,(vlSelfRef.top__DOT__DRAM__DOT__mem[120]),32);
    bufp->fullIData(oldp+145,(vlSelfRef.top__DOT__DRAM__DOT__mem[121]),32);
    bufp->fullIData(oldp+146,(vlSelfRef.top__DOT__DRAM__DOT__mem[122]),32);
    bufp->fullIData(oldp+147,(vlSelfRef.top__DOT__DRAM__DOT__mem[123]),32);
    bufp->fullIData(oldp+148,(vlSelfRef.top__DOT__DRAM__DOT__mem[124]),32);
    bufp->fullIData(oldp+149,(vlSelfRef.top__DOT__DRAM__DOT__mem[125]),32);
    bufp->fullIData(oldp+150,(vlSelfRef.top__DOT__DRAM__DOT__mem[126]),32);
    bufp->fullIData(oldp+151,(vlSelfRef.top__DOT__DRAM__DOT__mem[127]),32);
    bufp->fullIData(oldp+152,(vlSelfRef.top__DOT__DRAM__DOT__mem[128]),32);
    bufp->fullIData(oldp+153,(vlSelfRef.top__DOT__DRAM__DOT__mem[129]),32);
    bufp->fullIData(oldp+154,(vlSelfRef.top__DOT__DRAM__DOT__mem[130]),32);
    bufp->fullIData(oldp+155,(vlSelfRef.top__DOT__DRAM__DOT__mem[131]),32);
    bufp->fullIData(oldp+156,(vlSelfRef.top__DOT__DRAM__DOT__mem[132]),32);
    bufp->fullIData(oldp+157,(vlSelfRef.top__DOT__DRAM__DOT__mem[133]),32);
    bufp->fullIData(oldp+158,(vlSelfRef.top__DOT__DRAM__DOT__mem[134]),32);
    bufp->fullIData(oldp+159,(vlSelfRef.top__DOT__DRAM__DOT__mem[135]),32);
    bufp->fullIData(oldp+160,(vlSelfRef.top__DOT__DRAM__DOT__mem[136]),32);
    bufp->fullIData(oldp+161,(vlSelfRef.top__DOT__DRAM__DOT__mem[137]),32);
    bufp->fullIData(oldp+162,(vlSelfRef.top__DOT__DRAM__DOT__mem[138]),32);
    bufp->fullIData(oldp+163,(vlSelfRef.top__DOT__DRAM__DOT__mem[139]),32);
    bufp->fullIData(oldp+164,(vlSelfRef.top__DOT__DRAM__DOT__mem[140]),32);
    bufp->fullIData(oldp+165,(vlSelfRef.top__DOT__DRAM__DOT__mem[141]),32);
    bufp->fullIData(oldp+166,(vlSelfRef.top__DOT__DRAM__DOT__mem[142]),32);
    bufp->fullIData(oldp+167,(vlSelfRef.top__DOT__DRAM__DOT__mem[143]),32);
    bufp->fullIData(oldp+168,(vlSelfRef.top__DOT__DRAM__DOT__mem[144]),32);
    bufp->fullIData(oldp+169,(vlSelfRef.top__DOT__DRAM__DOT__mem[145]),32);
    bufp->fullIData(oldp+170,(vlSelfRef.top__DOT__DRAM__DOT__mem[146]),32);
    bufp->fullIData(oldp+171,(vlSelfRef.top__DOT__DRAM__DOT__mem[147]),32);
    bufp->fullIData(oldp+172,(vlSelfRef.top__DOT__DRAM__DOT__mem[148]),32);
    bufp->fullIData(oldp+173,(vlSelfRef.top__DOT__DRAM__DOT__mem[149]),32);
    bufp->fullIData(oldp+174,(vlSelfRef.top__DOT__DRAM__DOT__mem[150]),32);
    bufp->fullIData(oldp+175,(vlSelfRef.top__DOT__DRAM__DOT__mem[151]),32);
    bufp->fullIData(oldp+176,(vlSelfRef.top__DOT__DRAM__DOT__mem[152]),32);
    bufp->fullIData(oldp+177,(vlSelfRef.top__DOT__DRAM__DOT__mem[153]),32);
    bufp->fullIData(oldp+178,(vlSelfRef.top__DOT__DRAM__DOT__mem[154]),32);
    bufp->fullIData(oldp+179,(vlSelfRef.top__DOT__DRAM__DOT__mem[155]),32);
    bufp->fullIData(oldp+180,(vlSelfRef.top__DOT__DRAM__DOT__mem[156]),32);
    bufp->fullIData(oldp+181,(vlSelfRef.top__DOT__DRAM__DOT__mem[157]),32);
    bufp->fullIData(oldp+182,(vlSelfRef.top__DOT__DRAM__DOT__mem[158]),32);
    bufp->fullIData(oldp+183,(vlSelfRef.top__DOT__DRAM__DOT__mem[159]),32);
    bufp->fullIData(oldp+184,(vlSelfRef.top__DOT__DRAM__DOT__mem[160]),32);
    bufp->fullIData(oldp+185,(vlSelfRef.top__DOT__DRAM__DOT__mem[161]),32);
    bufp->fullIData(oldp+186,(vlSelfRef.top__DOT__DRAM__DOT__mem[162]),32);
    bufp->fullIData(oldp+187,(vlSelfRef.top__DOT__DRAM__DOT__mem[163]),32);
    bufp->fullIData(oldp+188,(vlSelfRef.top__DOT__DRAM__DOT__mem[164]),32);
    bufp->fullIData(oldp+189,(vlSelfRef.top__DOT__DRAM__DOT__mem[165]),32);
    bufp->fullIData(oldp+190,(vlSelfRef.top__DOT__DRAM__DOT__mem[166]),32);
    bufp->fullIData(oldp+191,(vlSelfRef.top__DOT__DRAM__DOT__mem[167]),32);
    bufp->fullIData(oldp+192,(vlSelfRef.top__DOT__DRAM__DOT__mem[168]),32);
    bufp->fullIData(oldp+193,(vlSelfRef.top__DOT__DRAM__DOT__mem[169]),32);
    bufp->fullIData(oldp+194,(vlSelfRef.top__DOT__DRAM__DOT__mem[170]),32);
    bufp->fullIData(oldp+195,(vlSelfRef.top__DOT__DRAM__DOT__mem[171]),32);
    bufp->fullIData(oldp+196,(vlSelfRef.top__DOT__DRAM__DOT__mem[172]),32);
    bufp->fullIData(oldp+197,(vlSelfRef.top__DOT__DRAM__DOT__mem[173]),32);
    bufp->fullIData(oldp+198,(vlSelfRef.top__DOT__DRAM__DOT__mem[174]),32);
    bufp->fullIData(oldp+199,(vlSelfRef.top__DOT__DRAM__DOT__mem[175]),32);
    bufp->fullIData(oldp+200,(vlSelfRef.top__DOT__DRAM__DOT__mem[176]),32);
    bufp->fullIData(oldp+201,(vlSelfRef.top__DOT__DRAM__DOT__mem[177]),32);
    bufp->fullIData(oldp+202,(vlSelfRef.top__DOT__DRAM__DOT__mem[178]),32);
    bufp->fullIData(oldp+203,(vlSelfRef.top__DOT__DRAM__DOT__mem[179]),32);
    bufp->fullIData(oldp+204,(vlSelfRef.top__DOT__DRAM__DOT__mem[180]),32);
    bufp->fullIData(oldp+205,(vlSelfRef.top__DOT__DRAM__DOT__mem[181]),32);
    bufp->fullIData(oldp+206,(vlSelfRef.top__DOT__DRAM__DOT__mem[182]),32);
    bufp->fullIData(oldp+207,(vlSelfRef.top__DOT__DRAM__DOT__mem[183]),32);
    bufp->fullIData(oldp+208,(vlSelfRef.top__DOT__DRAM__DOT__mem[184]),32);
    bufp->fullIData(oldp+209,(vlSelfRef.top__DOT__DRAM__DOT__mem[185]),32);
    bufp->fullIData(oldp+210,(vlSelfRef.top__DOT__DRAM__DOT__mem[186]),32);
    bufp->fullIData(oldp+211,(vlSelfRef.top__DOT__DRAM__DOT__mem[187]),32);
    bufp->fullIData(oldp+212,(vlSelfRef.top__DOT__DRAM__DOT__mem[188]),32);
    bufp->fullIData(oldp+213,(vlSelfRef.top__DOT__DRAM__DOT__mem[189]),32);
    bufp->fullIData(oldp+214,(vlSelfRef.top__DOT__DRAM__DOT__mem[190]),32);
    bufp->fullIData(oldp+215,(vlSelfRef.top__DOT__DRAM__DOT__mem[191]),32);
    bufp->fullIData(oldp+216,(vlSelfRef.top__DOT__DRAM__DOT__mem[192]),32);
    bufp->fullIData(oldp+217,(vlSelfRef.top__DOT__DRAM__DOT__mem[193]),32);
    bufp->fullIData(oldp+218,(vlSelfRef.top__DOT__DRAM__DOT__mem[194]),32);
    bufp->fullIData(oldp+219,(vlSelfRef.top__DOT__DRAM__DOT__mem[195]),32);
    bufp->fullIData(oldp+220,(vlSelfRef.top__DOT__DRAM__DOT__mem[196]),32);
    bufp->fullIData(oldp+221,(vlSelfRef.top__DOT__DRAM__DOT__mem[197]),32);
    bufp->fullIData(oldp+222,(vlSelfRef.top__DOT__DRAM__DOT__mem[198]),32);
    bufp->fullIData(oldp+223,(vlSelfRef.top__DOT__DRAM__DOT__mem[199]),32);
    bufp->fullIData(oldp+224,(vlSelfRef.top__DOT__DRAM__DOT__mem[200]),32);
    bufp->fullIData(oldp+225,(vlSelfRef.top__DOT__DRAM__DOT__mem[201]),32);
    bufp->fullIData(oldp+226,(vlSelfRef.top__DOT__DRAM__DOT__mem[202]),32);
    bufp->fullIData(oldp+227,(vlSelfRef.top__DOT__DRAM__DOT__mem[203]),32);
    bufp->fullIData(oldp+228,(vlSelfRef.top__DOT__DRAM__DOT__mem[204]),32);
    bufp->fullIData(oldp+229,(vlSelfRef.top__DOT__DRAM__DOT__mem[205]),32);
    bufp->fullIData(oldp+230,(vlSelfRef.top__DOT__DRAM__DOT__mem[206]),32);
    bufp->fullIData(oldp+231,(vlSelfRef.top__DOT__DRAM__DOT__mem[207]),32);
    bufp->fullIData(oldp+232,(vlSelfRef.top__DOT__DRAM__DOT__mem[208]),32);
    bufp->fullIData(oldp+233,(vlSelfRef.top__DOT__DRAM__DOT__mem[209]),32);
    bufp->fullIData(oldp+234,(vlSelfRef.top__DOT__DRAM__DOT__mem[210]),32);
    bufp->fullIData(oldp+235,(vlSelfRef.top__DOT__DRAM__DOT__mem[211]),32);
    bufp->fullIData(oldp+236,(vlSelfRef.top__DOT__DRAM__DOT__mem[212]),32);
    bufp->fullIData(oldp+237,(vlSelfRef.top__DOT__DRAM__DOT__mem[213]),32);
    bufp->fullIData(oldp+238,(vlSelfRef.top__DOT__DRAM__DOT__mem[214]),32);
    bufp->fullIData(oldp+239,(vlSelfRef.top__DOT__DRAM__DOT__mem[215]),32);
    bufp->fullIData(oldp+240,(vlSelfRef.top__DOT__DRAM__DOT__mem[216]),32);
    bufp->fullIData(oldp+241,(vlSelfRef.top__DOT__DRAM__DOT__mem[217]),32);
    bufp->fullIData(oldp+242,(vlSelfRef.top__DOT__DRAM__DOT__mem[218]),32);
    bufp->fullIData(oldp+243,(vlSelfRef.top__DOT__DRAM__DOT__mem[219]),32);
    bufp->fullIData(oldp+244,(vlSelfRef.top__DOT__DRAM__DOT__mem[220]),32);
    bufp->fullIData(oldp+245,(vlSelfRef.top__DOT__DRAM__DOT__mem[221]),32);
    bufp->fullIData(oldp+246,(vlSelfRef.top__DOT__DRAM__DOT__mem[222]),32);
    bufp->fullIData(oldp+247,(vlSelfRef.top__DOT__DRAM__DOT__mem[223]),32);
    bufp->fullIData(oldp+248,(vlSelfRef.top__DOT__DRAM__DOT__mem[224]),32);
    bufp->fullIData(oldp+249,(vlSelfRef.top__DOT__DRAM__DOT__mem[225]),32);
    bufp->fullIData(oldp+250,(vlSelfRef.top__DOT__DRAM__DOT__mem[226]),32);
    bufp->fullIData(oldp+251,(vlSelfRef.top__DOT__DRAM__DOT__mem[227]),32);
    bufp->fullIData(oldp+252,(vlSelfRef.top__DOT__DRAM__DOT__mem[228]),32);
    bufp->fullIData(oldp+253,(vlSelfRef.top__DOT__DRAM__DOT__mem[229]),32);
    bufp->fullIData(oldp+254,(vlSelfRef.top__DOT__DRAM__DOT__mem[230]),32);
    bufp->fullIData(oldp+255,(vlSelfRef.top__DOT__DRAM__DOT__mem[231]),32);
    bufp->fullIData(oldp+256,(vlSelfRef.top__DOT__DRAM__DOT__mem[232]),32);
    bufp->fullIData(oldp+257,(vlSelfRef.top__DOT__DRAM__DOT__mem[233]),32);
    bufp->fullIData(oldp+258,(vlSelfRef.top__DOT__DRAM__DOT__mem[234]),32);
    bufp->fullIData(oldp+259,(vlSelfRef.top__DOT__DRAM__DOT__mem[235]),32);
    bufp->fullIData(oldp+260,(vlSelfRef.top__DOT__DRAM__DOT__mem[236]),32);
    bufp->fullIData(oldp+261,(vlSelfRef.top__DOT__DRAM__DOT__mem[237]),32);
    bufp->fullIData(oldp+262,(vlSelfRef.top__DOT__DRAM__DOT__mem[238]),32);
    bufp->fullIData(oldp+263,(vlSelfRef.top__DOT__DRAM__DOT__mem[239]),32);
    bufp->fullIData(oldp+264,(vlSelfRef.top__DOT__DRAM__DOT__mem[240]),32);
    bufp->fullIData(oldp+265,(vlSelfRef.top__DOT__DRAM__DOT__mem[241]),32);
    bufp->fullIData(oldp+266,(vlSelfRef.top__DOT__DRAM__DOT__mem[242]),32);
    bufp->fullIData(oldp+267,(vlSelfRef.top__DOT__DRAM__DOT__mem[243]),32);
    bufp->fullIData(oldp+268,(vlSelfRef.top__DOT__DRAM__DOT__mem[244]),32);
    bufp->fullIData(oldp+269,(vlSelfRef.top__DOT__DRAM__DOT__mem[245]),32);
    bufp->fullIData(oldp+270,(vlSelfRef.top__DOT__DRAM__DOT__mem[246]),32);
    bufp->fullIData(oldp+271,(vlSelfRef.top__DOT__DRAM__DOT__mem[247]),32);
    bufp->fullIData(oldp+272,(vlSelfRef.top__DOT__DRAM__DOT__mem[248]),32);
    bufp->fullIData(oldp+273,(vlSelfRef.top__DOT__DRAM__DOT__mem[249]),32);
    bufp->fullIData(oldp+274,(vlSelfRef.top__DOT__DRAM__DOT__mem[250]),32);
    bufp->fullIData(oldp+275,(vlSelfRef.top__DOT__DRAM__DOT__mem[251]),32);
    bufp->fullIData(oldp+276,(vlSelfRef.top__DOT__DRAM__DOT__mem[252]),32);
    bufp->fullIData(oldp+277,(vlSelfRef.top__DOT__DRAM__DOT__mem[253]),32);
    bufp->fullIData(oldp+278,(vlSelfRef.top__DOT__DRAM__DOT__mem[254]),32);
    bufp->fullIData(oldp+279,(vlSelfRef.top__DOT__DRAM__DOT__mem[255]),32);
    bufp->fullCData(oldp+280,((0xffU & (vlSelfRef.top__DOT__data_mem_addr 
                                        >> 2U))),8);
    bufp->fullBit(oldp+281,((0x400U <= vlSelfRef.top__DOT__data_mem_addr)));
    bufp->fullCData(oldp+282,((0x1fU & (vlSelfRef.top__DOT__ins_out 
                                        >> 0xfU))),5);
    bufp->fullCData(oldp+283,((0x1fU & (vlSelfRef.top__DOT__ins_out 
                                        >> 0x14U))),5);
    bufp->fullCData(oldp+284,((0x1fU & (vlSelfRef.top__DOT__ins_out 
                                        >> 7U))),5);
    bufp->fullIData(oldp+285,(vlSelfRef.top__DOT__EU__DOT__target_addr),32);
    bufp->fullIData(oldp+286,(vlSelfRef.top__DOT__IRAM__DOT__mem[0]),32);
    bufp->fullIData(oldp+287,(vlSelfRef.top__DOT__IRAM__DOT__mem[1]),32);
    bufp->fullIData(oldp+288,(vlSelfRef.top__DOT__IRAM__DOT__mem[2]),32);
    bufp->fullIData(oldp+289,(vlSelfRef.top__DOT__IRAM__DOT__mem[3]),32);
    bufp->fullIData(oldp+290,(vlSelfRef.top__DOT__IRAM__DOT__mem[4]),32);
    bufp->fullIData(oldp+291,(vlSelfRef.top__DOT__IRAM__DOT__mem[5]),32);
    bufp->fullIData(oldp+292,(vlSelfRef.top__DOT__IRAM__DOT__mem[6]),32);
    bufp->fullIData(oldp+293,(vlSelfRef.top__DOT__IRAM__DOT__mem[7]),32);
    bufp->fullIData(oldp+294,(vlSelfRef.top__DOT__IRAM__DOT__mem[8]),32);
    bufp->fullIData(oldp+295,(vlSelfRef.top__DOT__IRAM__DOT__mem[9]),32);
    bufp->fullIData(oldp+296,(vlSelfRef.top__DOT__IRAM__DOT__mem[10]),32);
    bufp->fullIData(oldp+297,(vlSelfRef.top__DOT__IRAM__DOT__mem[11]),32);
    bufp->fullIData(oldp+298,(vlSelfRef.top__DOT__IRAM__DOT__mem[12]),32);
    bufp->fullIData(oldp+299,(vlSelfRef.top__DOT__IRAM__DOT__mem[13]),32);
    bufp->fullIData(oldp+300,(vlSelfRef.top__DOT__IRAM__DOT__mem[14]),32);
    bufp->fullIData(oldp+301,(vlSelfRef.top__DOT__IRAM__DOT__mem[15]),32);
    bufp->fullIData(oldp+302,(vlSelfRef.top__DOT__IRAM__DOT__mem[16]),32);
    bufp->fullIData(oldp+303,(vlSelfRef.top__DOT__IRAM__DOT__mem[17]),32);
    bufp->fullIData(oldp+304,(vlSelfRef.top__DOT__IRAM__DOT__mem[18]),32);
    bufp->fullIData(oldp+305,(vlSelfRef.top__DOT__IRAM__DOT__mem[19]),32);
    bufp->fullIData(oldp+306,(vlSelfRef.top__DOT__IRAM__DOT__mem[20]),32);
    bufp->fullIData(oldp+307,(vlSelfRef.top__DOT__IRAM__DOT__mem[21]),32);
    bufp->fullIData(oldp+308,(vlSelfRef.top__DOT__IRAM__DOT__mem[22]),32);
    bufp->fullIData(oldp+309,(vlSelfRef.top__DOT__IRAM__DOT__mem[23]),32);
    bufp->fullIData(oldp+310,(vlSelfRef.top__DOT__IRAM__DOT__mem[24]),32);
    bufp->fullIData(oldp+311,(vlSelfRef.top__DOT__IRAM__DOT__mem[25]),32);
    bufp->fullIData(oldp+312,(vlSelfRef.top__DOT__IRAM__DOT__mem[26]),32);
    bufp->fullIData(oldp+313,(vlSelfRef.top__DOT__IRAM__DOT__mem[27]),32);
    bufp->fullIData(oldp+314,(vlSelfRef.top__DOT__IRAM__DOT__mem[28]),32);
    bufp->fullIData(oldp+315,(vlSelfRef.top__DOT__IRAM__DOT__mem[29]),32);
    bufp->fullIData(oldp+316,(vlSelfRef.top__DOT__IRAM__DOT__mem[30]),32);
    bufp->fullIData(oldp+317,(vlSelfRef.top__DOT__IRAM__DOT__mem[31]),32);
    bufp->fullIData(oldp+318,(vlSelfRef.top__DOT__IRAM__DOT__mem[32]),32);
    bufp->fullIData(oldp+319,(vlSelfRef.top__DOT__IRAM__DOT__mem[33]),32);
    bufp->fullIData(oldp+320,(vlSelfRef.top__DOT__IRAM__DOT__mem[34]),32);
    bufp->fullIData(oldp+321,(vlSelfRef.top__DOT__IRAM__DOT__mem[35]),32);
    bufp->fullIData(oldp+322,(vlSelfRef.top__DOT__IRAM__DOT__mem[36]),32);
    bufp->fullIData(oldp+323,(vlSelfRef.top__DOT__IRAM__DOT__mem[37]),32);
    bufp->fullIData(oldp+324,(vlSelfRef.top__DOT__IRAM__DOT__mem[38]),32);
    bufp->fullIData(oldp+325,(vlSelfRef.top__DOT__IRAM__DOT__mem[39]),32);
    bufp->fullIData(oldp+326,(vlSelfRef.top__DOT__IRAM__DOT__mem[40]),32);
    bufp->fullIData(oldp+327,(vlSelfRef.top__DOT__IRAM__DOT__mem[41]),32);
    bufp->fullIData(oldp+328,(vlSelfRef.top__DOT__IRAM__DOT__mem[42]),32);
    bufp->fullIData(oldp+329,(vlSelfRef.top__DOT__IRAM__DOT__mem[43]),32);
    bufp->fullIData(oldp+330,(vlSelfRef.top__DOT__IRAM__DOT__mem[44]),32);
    bufp->fullIData(oldp+331,(vlSelfRef.top__DOT__IRAM__DOT__mem[45]),32);
    bufp->fullIData(oldp+332,(vlSelfRef.top__DOT__IRAM__DOT__mem[46]),32);
    bufp->fullIData(oldp+333,(vlSelfRef.top__DOT__IRAM__DOT__mem[47]),32);
    bufp->fullIData(oldp+334,(vlSelfRef.top__DOT__IRAM__DOT__mem[48]),32);
    bufp->fullIData(oldp+335,(vlSelfRef.top__DOT__IRAM__DOT__mem[49]),32);
    bufp->fullIData(oldp+336,(vlSelfRef.top__DOT__IRAM__DOT__mem[50]),32);
    bufp->fullIData(oldp+337,(vlSelfRef.top__DOT__IRAM__DOT__mem[51]),32);
    bufp->fullIData(oldp+338,(vlSelfRef.top__DOT__IRAM__DOT__mem[52]),32);
    bufp->fullIData(oldp+339,(vlSelfRef.top__DOT__IRAM__DOT__mem[53]),32);
    bufp->fullIData(oldp+340,(vlSelfRef.top__DOT__IRAM__DOT__mem[54]),32);
    bufp->fullIData(oldp+341,(vlSelfRef.top__DOT__IRAM__DOT__mem[55]),32);
    bufp->fullIData(oldp+342,(vlSelfRef.top__DOT__IRAM__DOT__mem[56]),32);
    bufp->fullIData(oldp+343,(vlSelfRef.top__DOT__IRAM__DOT__mem[57]),32);
    bufp->fullIData(oldp+344,(vlSelfRef.top__DOT__IRAM__DOT__mem[58]),32);
    bufp->fullIData(oldp+345,(vlSelfRef.top__DOT__IRAM__DOT__mem[59]),32);
    bufp->fullIData(oldp+346,(vlSelfRef.top__DOT__IRAM__DOT__mem[60]),32);
    bufp->fullIData(oldp+347,(vlSelfRef.top__DOT__IRAM__DOT__mem[61]),32);
    bufp->fullIData(oldp+348,(vlSelfRef.top__DOT__IRAM__DOT__mem[62]),32);
    bufp->fullIData(oldp+349,(vlSelfRef.top__DOT__IRAM__DOT__mem[63]),32);
    bufp->fullIData(oldp+350,(vlSelfRef.top__DOT__IRAM__DOT__mem[64]),32);
    bufp->fullIData(oldp+351,(vlSelfRef.top__DOT__IRAM__DOT__mem[65]),32);
    bufp->fullIData(oldp+352,(vlSelfRef.top__DOT__IRAM__DOT__mem[66]),32);
    bufp->fullIData(oldp+353,(vlSelfRef.top__DOT__IRAM__DOT__mem[67]),32);
    bufp->fullIData(oldp+354,(vlSelfRef.top__DOT__IRAM__DOT__mem[68]),32);
    bufp->fullIData(oldp+355,(vlSelfRef.top__DOT__IRAM__DOT__mem[69]),32);
    bufp->fullIData(oldp+356,(vlSelfRef.top__DOT__IRAM__DOT__mem[70]),32);
    bufp->fullIData(oldp+357,(vlSelfRef.top__DOT__IRAM__DOT__mem[71]),32);
    bufp->fullIData(oldp+358,(vlSelfRef.top__DOT__IRAM__DOT__mem[72]),32);
    bufp->fullIData(oldp+359,(vlSelfRef.top__DOT__IRAM__DOT__mem[73]),32);
    bufp->fullIData(oldp+360,(vlSelfRef.top__DOT__IRAM__DOT__mem[74]),32);
    bufp->fullIData(oldp+361,(vlSelfRef.top__DOT__IRAM__DOT__mem[75]),32);
    bufp->fullIData(oldp+362,(vlSelfRef.top__DOT__IRAM__DOT__mem[76]),32);
    bufp->fullIData(oldp+363,(vlSelfRef.top__DOT__IRAM__DOT__mem[77]),32);
    bufp->fullIData(oldp+364,(vlSelfRef.top__DOT__IRAM__DOT__mem[78]),32);
    bufp->fullIData(oldp+365,(vlSelfRef.top__DOT__IRAM__DOT__mem[79]),32);
    bufp->fullIData(oldp+366,(vlSelfRef.top__DOT__IRAM__DOT__mem[80]),32);
    bufp->fullIData(oldp+367,(vlSelfRef.top__DOT__IRAM__DOT__mem[81]),32);
    bufp->fullIData(oldp+368,(vlSelfRef.top__DOT__IRAM__DOT__mem[82]),32);
    bufp->fullIData(oldp+369,(vlSelfRef.top__DOT__IRAM__DOT__mem[83]),32);
    bufp->fullIData(oldp+370,(vlSelfRef.top__DOT__IRAM__DOT__mem[84]),32);
    bufp->fullIData(oldp+371,(vlSelfRef.top__DOT__IRAM__DOT__mem[85]),32);
    bufp->fullIData(oldp+372,(vlSelfRef.top__DOT__IRAM__DOT__mem[86]),32);
    bufp->fullIData(oldp+373,(vlSelfRef.top__DOT__IRAM__DOT__mem[87]),32);
    bufp->fullIData(oldp+374,(vlSelfRef.top__DOT__IRAM__DOT__mem[88]),32);
    bufp->fullIData(oldp+375,(vlSelfRef.top__DOT__IRAM__DOT__mem[89]),32);
    bufp->fullIData(oldp+376,(vlSelfRef.top__DOT__IRAM__DOT__mem[90]),32);
    bufp->fullIData(oldp+377,(vlSelfRef.top__DOT__IRAM__DOT__mem[91]),32);
    bufp->fullIData(oldp+378,(vlSelfRef.top__DOT__IRAM__DOT__mem[92]),32);
    bufp->fullIData(oldp+379,(vlSelfRef.top__DOT__IRAM__DOT__mem[93]),32);
    bufp->fullIData(oldp+380,(vlSelfRef.top__DOT__IRAM__DOT__mem[94]),32);
    bufp->fullIData(oldp+381,(vlSelfRef.top__DOT__IRAM__DOT__mem[95]),32);
    bufp->fullIData(oldp+382,(vlSelfRef.top__DOT__IRAM__DOT__mem[96]),32);
    bufp->fullIData(oldp+383,(vlSelfRef.top__DOT__IRAM__DOT__mem[97]),32);
    bufp->fullIData(oldp+384,(vlSelfRef.top__DOT__IRAM__DOT__mem[98]),32);
    bufp->fullIData(oldp+385,(vlSelfRef.top__DOT__IRAM__DOT__mem[99]),32);
    bufp->fullIData(oldp+386,(vlSelfRef.top__DOT__IRAM__DOT__mem[100]),32);
    bufp->fullIData(oldp+387,(vlSelfRef.top__DOT__IRAM__DOT__mem[101]),32);
    bufp->fullIData(oldp+388,(vlSelfRef.top__DOT__IRAM__DOT__mem[102]),32);
    bufp->fullIData(oldp+389,(vlSelfRef.top__DOT__IRAM__DOT__mem[103]),32);
    bufp->fullIData(oldp+390,(vlSelfRef.top__DOT__IRAM__DOT__mem[104]),32);
    bufp->fullIData(oldp+391,(vlSelfRef.top__DOT__IRAM__DOT__mem[105]),32);
    bufp->fullIData(oldp+392,(vlSelfRef.top__DOT__IRAM__DOT__mem[106]),32);
    bufp->fullIData(oldp+393,(vlSelfRef.top__DOT__IRAM__DOT__mem[107]),32);
    bufp->fullIData(oldp+394,(vlSelfRef.top__DOT__IRAM__DOT__mem[108]),32);
    bufp->fullIData(oldp+395,(vlSelfRef.top__DOT__IRAM__DOT__mem[109]),32);
    bufp->fullIData(oldp+396,(vlSelfRef.top__DOT__IRAM__DOT__mem[110]),32);
    bufp->fullIData(oldp+397,(vlSelfRef.top__DOT__IRAM__DOT__mem[111]),32);
    bufp->fullIData(oldp+398,(vlSelfRef.top__DOT__IRAM__DOT__mem[112]),32);
    bufp->fullIData(oldp+399,(vlSelfRef.top__DOT__IRAM__DOT__mem[113]),32);
    bufp->fullIData(oldp+400,(vlSelfRef.top__DOT__IRAM__DOT__mem[114]),32);
    bufp->fullIData(oldp+401,(vlSelfRef.top__DOT__IRAM__DOT__mem[115]),32);
    bufp->fullIData(oldp+402,(vlSelfRef.top__DOT__IRAM__DOT__mem[116]),32);
    bufp->fullIData(oldp+403,(vlSelfRef.top__DOT__IRAM__DOT__mem[117]),32);
    bufp->fullIData(oldp+404,(vlSelfRef.top__DOT__IRAM__DOT__mem[118]),32);
    bufp->fullIData(oldp+405,(vlSelfRef.top__DOT__IRAM__DOT__mem[119]),32);
    bufp->fullIData(oldp+406,(vlSelfRef.top__DOT__IRAM__DOT__mem[120]),32);
    bufp->fullIData(oldp+407,(vlSelfRef.top__DOT__IRAM__DOT__mem[121]),32);
    bufp->fullIData(oldp+408,(vlSelfRef.top__DOT__IRAM__DOT__mem[122]),32);
    bufp->fullIData(oldp+409,(vlSelfRef.top__DOT__IRAM__DOT__mem[123]),32);
    bufp->fullIData(oldp+410,(vlSelfRef.top__DOT__IRAM__DOT__mem[124]),32);
    bufp->fullIData(oldp+411,(vlSelfRef.top__DOT__IRAM__DOT__mem[125]),32);
    bufp->fullIData(oldp+412,(vlSelfRef.top__DOT__IRAM__DOT__mem[126]),32);
    bufp->fullIData(oldp+413,(vlSelfRef.top__DOT__IRAM__DOT__mem[127]),32);
    bufp->fullIData(oldp+414,(vlSelfRef.top__DOT__IRAM__DOT__mem[128]),32);
    bufp->fullIData(oldp+415,(vlSelfRef.top__DOT__IRAM__DOT__mem[129]),32);
    bufp->fullIData(oldp+416,(vlSelfRef.top__DOT__IRAM__DOT__mem[130]),32);
    bufp->fullIData(oldp+417,(vlSelfRef.top__DOT__IRAM__DOT__mem[131]),32);
    bufp->fullIData(oldp+418,(vlSelfRef.top__DOT__IRAM__DOT__mem[132]),32);
    bufp->fullIData(oldp+419,(vlSelfRef.top__DOT__IRAM__DOT__mem[133]),32);
    bufp->fullIData(oldp+420,(vlSelfRef.top__DOT__IRAM__DOT__mem[134]),32);
    bufp->fullIData(oldp+421,(vlSelfRef.top__DOT__IRAM__DOT__mem[135]),32);
    bufp->fullIData(oldp+422,(vlSelfRef.top__DOT__IRAM__DOT__mem[136]),32);
    bufp->fullIData(oldp+423,(vlSelfRef.top__DOT__IRAM__DOT__mem[137]),32);
    bufp->fullIData(oldp+424,(vlSelfRef.top__DOT__IRAM__DOT__mem[138]),32);
    bufp->fullIData(oldp+425,(vlSelfRef.top__DOT__IRAM__DOT__mem[139]),32);
    bufp->fullIData(oldp+426,(vlSelfRef.top__DOT__IRAM__DOT__mem[140]),32);
    bufp->fullIData(oldp+427,(vlSelfRef.top__DOT__IRAM__DOT__mem[141]),32);
    bufp->fullIData(oldp+428,(vlSelfRef.top__DOT__IRAM__DOT__mem[142]),32);
    bufp->fullIData(oldp+429,(vlSelfRef.top__DOT__IRAM__DOT__mem[143]),32);
    bufp->fullIData(oldp+430,(vlSelfRef.top__DOT__IRAM__DOT__mem[144]),32);
    bufp->fullIData(oldp+431,(vlSelfRef.top__DOT__IRAM__DOT__mem[145]),32);
    bufp->fullIData(oldp+432,(vlSelfRef.top__DOT__IRAM__DOT__mem[146]),32);
    bufp->fullIData(oldp+433,(vlSelfRef.top__DOT__IRAM__DOT__mem[147]),32);
    bufp->fullIData(oldp+434,(vlSelfRef.top__DOT__IRAM__DOT__mem[148]),32);
    bufp->fullIData(oldp+435,(vlSelfRef.top__DOT__IRAM__DOT__mem[149]),32);
    bufp->fullIData(oldp+436,(vlSelfRef.top__DOT__IRAM__DOT__mem[150]),32);
    bufp->fullIData(oldp+437,(vlSelfRef.top__DOT__IRAM__DOT__mem[151]),32);
    bufp->fullIData(oldp+438,(vlSelfRef.top__DOT__IRAM__DOT__mem[152]),32);
    bufp->fullIData(oldp+439,(vlSelfRef.top__DOT__IRAM__DOT__mem[153]),32);
    bufp->fullIData(oldp+440,(vlSelfRef.top__DOT__IRAM__DOT__mem[154]),32);
    bufp->fullIData(oldp+441,(vlSelfRef.top__DOT__IRAM__DOT__mem[155]),32);
    bufp->fullIData(oldp+442,(vlSelfRef.top__DOT__IRAM__DOT__mem[156]),32);
    bufp->fullIData(oldp+443,(vlSelfRef.top__DOT__IRAM__DOT__mem[157]),32);
    bufp->fullIData(oldp+444,(vlSelfRef.top__DOT__IRAM__DOT__mem[158]),32);
    bufp->fullIData(oldp+445,(vlSelfRef.top__DOT__IRAM__DOT__mem[159]),32);
    bufp->fullIData(oldp+446,(vlSelfRef.top__DOT__IRAM__DOT__mem[160]),32);
    bufp->fullIData(oldp+447,(vlSelfRef.top__DOT__IRAM__DOT__mem[161]),32);
    bufp->fullIData(oldp+448,(vlSelfRef.top__DOT__IRAM__DOT__mem[162]),32);
    bufp->fullIData(oldp+449,(vlSelfRef.top__DOT__IRAM__DOT__mem[163]),32);
    bufp->fullIData(oldp+450,(vlSelfRef.top__DOT__IRAM__DOT__mem[164]),32);
    bufp->fullIData(oldp+451,(vlSelfRef.top__DOT__IRAM__DOT__mem[165]),32);
    bufp->fullIData(oldp+452,(vlSelfRef.top__DOT__IRAM__DOT__mem[166]),32);
    bufp->fullIData(oldp+453,(vlSelfRef.top__DOT__IRAM__DOT__mem[167]),32);
    bufp->fullIData(oldp+454,(vlSelfRef.top__DOT__IRAM__DOT__mem[168]),32);
    bufp->fullIData(oldp+455,(vlSelfRef.top__DOT__IRAM__DOT__mem[169]),32);
    bufp->fullIData(oldp+456,(vlSelfRef.top__DOT__IRAM__DOT__mem[170]),32);
    bufp->fullIData(oldp+457,(vlSelfRef.top__DOT__IRAM__DOT__mem[171]),32);
    bufp->fullIData(oldp+458,(vlSelfRef.top__DOT__IRAM__DOT__mem[172]),32);
    bufp->fullIData(oldp+459,(vlSelfRef.top__DOT__IRAM__DOT__mem[173]),32);
    bufp->fullIData(oldp+460,(vlSelfRef.top__DOT__IRAM__DOT__mem[174]),32);
    bufp->fullIData(oldp+461,(vlSelfRef.top__DOT__IRAM__DOT__mem[175]),32);
    bufp->fullIData(oldp+462,(vlSelfRef.top__DOT__IRAM__DOT__mem[176]),32);
    bufp->fullIData(oldp+463,(vlSelfRef.top__DOT__IRAM__DOT__mem[177]),32);
    bufp->fullIData(oldp+464,(vlSelfRef.top__DOT__IRAM__DOT__mem[178]),32);
    bufp->fullIData(oldp+465,(vlSelfRef.top__DOT__IRAM__DOT__mem[179]),32);
    bufp->fullIData(oldp+466,(vlSelfRef.top__DOT__IRAM__DOT__mem[180]),32);
    bufp->fullIData(oldp+467,(vlSelfRef.top__DOT__IRAM__DOT__mem[181]),32);
    bufp->fullIData(oldp+468,(vlSelfRef.top__DOT__IRAM__DOT__mem[182]),32);
    bufp->fullIData(oldp+469,(vlSelfRef.top__DOT__IRAM__DOT__mem[183]),32);
    bufp->fullIData(oldp+470,(vlSelfRef.top__DOT__IRAM__DOT__mem[184]),32);
    bufp->fullIData(oldp+471,(vlSelfRef.top__DOT__IRAM__DOT__mem[185]),32);
    bufp->fullIData(oldp+472,(vlSelfRef.top__DOT__IRAM__DOT__mem[186]),32);
    bufp->fullIData(oldp+473,(vlSelfRef.top__DOT__IRAM__DOT__mem[187]),32);
    bufp->fullIData(oldp+474,(vlSelfRef.top__DOT__IRAM__DOT__mem[188]),32);
    bufp->fullIData(oldp+475,(vlSelfRef.top__DOT__IRAM__DOT__mem[189]),32);
    bufp->fullIData(oldp+476,(vlSelfRef.top__DOT__IRAM__DOT__mem[190]),32);
    bufp->fullIData(oldp+477,(vlSelfRef.top__DOT__IRAM__DOT__mem[191]),32);
    bufp->fullIData(oldp+478,(vlSelfRef.top__DOT__IRAM__DOT__mem[192]),32);
    bufp->fullIData(oldp+479,(vlSelfRef.top__DOT__IRAM__DOT__mem[193]),32);
    bufp->fullIData(oldp+480,(vlSelfRef.top__DOT__IRAM__DOT__mem[194]),32);
    bufp->fullIData(oldp+481,(vlSelfRef.top__DOT__IRAM__DOT__mem[195]),32);
    bufp->fullIData(oldp+482,(vlSelfRef.top__DOT__IRAM__DOT__mem[196]),32);
    bufp->fullIData(oldp+483,(vlSelfRef.top__DOT__IRAM__DOT__mem[197]),32);
    bufp->fullIData(oldp+484,(vlSelfRef.top__DOT__IRAM__DOT__mem[198]),32);
    bufp->fullIData(oldp+485,(vlSelfRef.top__DOT__IRAM__DOT__mem[199]),32);
    bufp->fullIData(oldp+486,(vlSelfRef.top__DOT__IRAM__DOT__mem[200]),32);
    bufp->fullIData(oldp+487,(vlSelfRef.top__DOT__IRAM__DOT__mem[201]),32);
    bufp->fullIData(oldp+488,(vlSelfRef.top__DOT__IRAM__DOT__mem[202]),32);
    bufp->fullIData(oldp+489,(vlSelfRef.top__DOT__IRAM__DOT__mem[203]),32);
    bufp->fullIData(oldp+490,(vlSelfRef.top__DOT__IRAM__DOT__mem[204]),32);
    bufp->fullIData(oldp+491,(vlSelfRef.top__DOT__IRAM__DOT__mem[205]),32);
    bufp->fullIData(oldp+492,(vlSelfRef.top__DOT__IRAM__DOT__mem[206]),32);
    bufp->fullIData(oldp+493,(vlSelfRef.top__DOT__IRAM__DOT__mem[207]),32);
    bufp->fullIData(oldp+494,(vlSelfRef.top__DOT__IRAM__DOT__mem[208]),32);
    bufp->fullIData(oldp+495,(vlSelfRef.top__DOT__IRAM__DOT__mem[209]),32);
    bufp->fullIData(oldp+496,(vlSelfRef.top__DOT__IRAM__DOT__mem[210]),32);
    bufp->fullIData(oldp+497,(vlSelfRef.top__DOT__IRAM__DOT__mem[211]),32);
    bufp->fullIData(oldp+498,(vlSelfRef.top__DOT__IRAM__DOT__mem[212]),32);
    bufp->fullIData(oldp+499,(vlSelfRef.top__DOT__IRAM__DOT__mem[213]),32);
    bufp->fullIData(oldp+500,(vlSelfRef.top__DOT__IRAM__DOT__mem[214]),32);
    bufp->fullIData(oldp+501,(vlSelfRef.top__DOT__IRAM__DOT__mem[215]),32);
    bufp->fullIData(oldp+502,(vlSelfRef.top__DOT__IRAM__DOT__mem[216]),32);
    bufp->fullIData(oldp+503,(vlSelfRef.top__DOT__IRAM__DOT__mem[217]),32);
    bufp->fullIData(oldp+504,(vlSelfRef.top__DOT__IRAM__DOT__mem[218]),32);
    bufp->fullIData(oldp+505,(vlSelfRef.top__DOT__IRAM__DOT__mem[219]),32);
    bufp->fullIData(oldp+506,(vlSelfRef.top__DOT__IRAM__DOT__mem[220]),32);
    bufp->fullIData(oldp+507,(vlSelfRef.top__DOT__IRAM__DOT__mem[221]),32);
    bufp->fullIData(oldp+508,(vlSelfRef.top__DOT__IRAM__DOT__mem[222]),32);
    bufp->fullIData(oldp+509,(vlSelfRef.top__DOT__IRAM__DOT__mem[223]),32);
    bufp->fullIData(oldp+510,(vlSelfRef.top__DOT__IRAM__DOT__mem[224]),32);
    bufp->fullIData(oldp+511,(vlSelfRef.top__DOT__IRAM__DOT__mem[225]),32);
    bufp->fullIData(oldp+512,(vlSelfRef.top__DOT__IRAM__DOT__mem[226]),32);
    bufp->fullIData(oldp+513,(vlSelfRef.top__DOT__IRAM__DOT__mem[227]),32);
    bufp->fullIData(oldp+514,(vlSelfRef.top__DOT__IRAM__DOT__mem[228]),32);
    bufp->fullIData(oldp+515,(vlSelfRef.top__DOT__IRAM__DOT__mem[229]),32);
    bufp->fullIData(oldp+516,(vlSelfRef.top__DOT__IRAM__DOT__mem[230]),32);
    bufp->fullIData(oldp+517,(vlSelfRef.top__DOT__IRAM__DOT__mem[231]),32);
    bufp->fullIData(oldp+518,(vlSelfRef.top__DOT__IRAM__DOT__mem[232]),32);
    bufp->fullIData(oldp+519,(vlSelfRef.top__DOT__IRAM__DOT__mem[233]),32);
    bufp->fullIData(oldp+520,(vlSelfRef.top__DOT__IRAM__DOT__mem[234]),32);
    bufp->fullIData(oldp+521,(vlSelfRef.top__DOT__IRAM__DOT__mem[235]),32);
    bufp->fullIData(oldp+522,(vlSelfRef.top__DOT__IRAM__DOT__mem[236]),32);
    bufp->fullIData(oldp+523,(vlSelfRef.top__DOT__IRAM__DOT__mem[237]),32);
    bufp->fullIData(oldp+524,(vlSelfRef.top__DOT__IRAM__DOT__mem[238]),32);
    bufp->fullIData(oldp+525,(vlSelfRef.top__DOT__IRAM__DOT__mem[239]),32);
    bufp->fullIData(oldp+526,(vlSelfRef.top__DOT__IRAM__DOT__mem[240]),32);
    bufp->fullIData(oldp+527,(vlSelfRef.top__DOT__IRAM__DOT__mem[241]),32);
    bufp->fullIData(oldp+528,(vlSelfRef.top__DOT__IRAM__DOT__mem[242]),32);
    bufp->fullIData(oldp+529,(vlSelfRef.top__DOT__IRAM__DOT__mem[243]),32);
    bufp->fullIData(oldp+530,(vlSelfRef.top__DOT__IRAM__DOT__mem[244]),32);
    bufp->fullIData(oldp+531,(vlSelfRef.top__DOT__IRAM__DOT__mem[245]),32);
    bufp->fullIData(oldp+532,(vlSelfRef.top__DOT__IRAM__DOT__mem[246]),32);
    bufp->fullIData(oldp+533,(vlSelfRef.top__DOT__IRAM__DOT__mem[247]),32);
    bufp->fullIData(oldp+534,(vlSelfRef.top__DOT__IRAM__DOT__mem[248]),32);
    bufp->fullIData(oldp+535,(vlSelfRef.top__DOT__IRAM__DOT__mem[249]),32);
    bufp->fullIData(oldp+536,(vlSelfRef.top__DOT__IRAM__DOT__mem[250]),32);
    bufp->fullIData(oldp+537,(vlSelfRef.top__DOT__IRAM__DOT__mem[251]),32);
    bufp->fullIData(oldp+538,(vlSelfRef.top__DOT__IRAM__DOT__mem[252]),32);
    bufp->fullIData(oldp+539,(vlSelfRef.top__DOT__IRAM__DOT__mem[253]),32);
    bufp->fullIData(oldp+540,(vlSelfRef.top__DOT__IRAM__DOT__mem[254]),32);
    bufp->fullIData(oldp+541,(vlSelfRef.top__DOT__IRAM__DOT__mem[255]),32);
    bufp->fullCData(oldp+542,((0xffU & (vlSelfRef.top__DOT__FU__DOT__PC 
                                        >> 2U))),8);
    bufp->fullIData(oldp+543,(vlSelfRef.top__DOT__reg_file__DOT__regs[0]),32);
    bufp->fullIData(oldp+544,(vlSelfRef.top__DOT__reg_file__DOT__regs[1]),32);
    bufp->fullIData(oldp+545,(vlSelfRef.top__DOT__reg_file__DOT__regs[2]),32);
    bufp->fullIData(oldp+546,(vlSelfRef.top__DOT__reg_file__DOT__regs[3]),32);
    bufp->fullIData(oldp+547,(vlSelfRef.top__DOT__reg_file__DOT__regs[4]),32);
    bufp->fullIData(oldp+548,(vlSelfRef.top__DOT__reg_file__DOT__regs[5]),32);
    bufp->fullIData(oldp+549,(vlSelfRef.top__DOT__reg_file__DOT__regs[6]),32);
    bufp->fullIData(oldp+550,(vlSelfRef.top__DOT__reg_file__DOT__regs[7]),32);
    bufp->fullIData(oldp+551,(vlSelfRef.top__DOT__reg_file__DOT__regs[8]),32);
    bufp->fullIData(oldp+552,(vlSelfRef.top__DOT__reg_file__DOT__regs[9]),32);
    bufp->fullIData(oldp+553,(vlSelfRef.top__DOT__reg_file__DOT__regs[10]),32);
    bufp->fullIData(oldp+554,(vlSelfRef.top__DOT__reg_file__DOT__regs[11]),32);
    bufp->fullIData(oldp+555,(vlSelfRef.top__DOT__reg_file__DOT__regs[12]),32);
    bufp->fullIData(oldp+556,(vlSelfRef.top__DOT__reg_file__DOT__regs[13]),32);
    bufp->fullIData(oldp+557,(vlSelfRef.top__DOT__reg_file__DOT__regs[14]),32);
    bufp->fullIData(oldp+558,(vlSelfRef.top__DOT__reg_file__DOT__regs[15]),32);
    bufp->fullIData(oldp+559,(vlSelfRef.top__DOT__reg_file__DOT__regs[16]),32);
    bufp->fullIData(oldp+560,(vlSelfRef.top__DOT__reg_file__DOT__regs[17]),32);
    bufp->fullIData(oldp+561,(vlSelfRef.top__DOT__reg_file__DOT__regs[18]),32);
    bufp->fullIData(oldp+562,(vlSelfRef.top__DOT__reg_file__DOT__regs[19]),32);
    bufp->fullIData(oldp+563,(vlSelfRef.top__DOT__reg_file__DOT__regs[20]),32);
    bufp->fullIData(oldp+564,(vlSelfRef.top__DOT__reg_file__DOT__regs[21]),32);
    bufp->fullIData(oldp+565,(vlSelfRef.top__DOT__reg_file__DOT__regs[22]),32);
    bufp->fullIData(oldp+566,(vlSelfRef.top__DOT__reg_file__DOT__regs[23]),32);
    bufp->fullIData(oldp+567,(vlSelfRef.top__DOT__reg_file__DOT__regs[24]),32);
    bufp->fullIData(oldp+568,(vlSelfRef.top__DOT__reg_file__DOT__regs[25]),32);
    bufp->fullIData(oldp+569,(vlSelfRef.top__DOT__reg_file__DOT__regs[26]),32);
    bufp->fullIData(oldp+570,(vlSelfRef.top__DOT__reg_file__DOT__regs[27]),32);
    bufp->fullIData(oldp+571,(vlSelfRef.top__DOT__reg_file__DOT__regs[28]),32);
    bufp->fullIData(oldp+572,(vlSelfRef.top__DOT__reg_file__DOT__regs[29]),32);
    bufp->fullIData(oldp+573,(vlSelfRef.top__DOT__reg_file__DOT__regs[30]),32);
    bufp->fullIData(oldp+574,(vlSelfRef.top__DOT__reg_file__DOT__regs[31]),32);
    bufp->fullBit(oldp+575,(vlSelfRef.clk));
    bufp->fullIData(oldp+576,(vlSelfRef.GPIO),32);
}
